Add lint.sh -c flag
Adds a -c flag to scripts/lint.sh that causes lints to be run from within the
ubuntu2604 container.  This ensures that the same version of shellcheck used
on the Ubuntu GitHub Actions runners is also what's used when running locally,
and it gives potential contributors a way to run lints without installing
extra packages on their host systems.

This also has the effect of ensuring ruff is invoked from the venv, so that
its pinned version is guaranteed to be used.

diff --git a/scripts/lib b/scripts/lib
--- a/scripts/lib
+++ b/scripts/lib
@@ -8,6 +8,40 @@ export TEST_VMS_S3_ENDPOINT
 TEST_VMS_S3_BUCKET='socklink-test-vms'
 export TEST_VMS_S3_BUCKET
 
+PYTHON_MIN=3.11
+PYTHON_BINS="python3.15 python3.14 python3.13 python3.12 python3.11 python3 python"
+
+python_version_at_least() {
+	result=$("$1" -c "import sys; print(float(f'{sys.version_info[0]}.{sys.version_info[1]}') >= $2)")
+	if [ "$result" != "True" ]; then
+		false
+	fi
+}
+
+# Searches Python binary candidate names for the first one matching our
+# minimum version requirement.
+get_python_bin() {
+	for bin in $PYTHON_BINS; do
+		if which "$bin" >/dev/null 2>&1 \
+				&& python_version_at_least "$bin" "$PYTHON_MIN"; then
+			ver=$("$bin" --version)
+			echo "Using bin $bin, version $ver" >&2
+			echo "$bin"
+			return
+		fi
+	done
+	echo "No supported Python version found, aborting" >&2
+	exit 1
+}
+
+setup_venv() {
+	if [ ! -d "${PROJECT}/.venv" ]; then
+		echo "Preparing venv"
+		py="$(get_python_bin)"
+		"$py" -m venv "${PROJECT}/.venv"
+	fi
+}
+
 find_docker() {
 	if podman -v >/dev/null 2>&1; then
 		which podman
@@ -39,6 +73,7 @@ pyproject.toml
 pyrightconfig.json
 requirements.txt
 scripts
+shellcheckrc
 socklink.sh
 tests
 "
